### ISSUE TITLE
fileencryption or encryptable on android-8.1.0_r11?

### ISSUE THREAD

**Issue by gwolf2u** [crdroidandroid/android_device_oneplus_msm8998-common#1]
https://github.com/crdroid-devices/android_device_oneplus_msm8998-common/blob/f422ffa977ca67707aff6cd54c6f8bdb7e8eb07a/init/vendor/etc/fstab.qcom#L10

@neobuddy89 
as of android-8.1.0_r11 TWRP can not read data partition
more info here https://github.com/invisiblek/android_frameworks_base/commit/926c1445fd8a79abe5ed497d8a705e84653bbc9f
think we should go by encryptable for a few build or wait for TWRP to update?

**Comment by neobuddy89** [comment]
We wait for TWRP. Encryptable is problematic for encrypted devices unlike Nexus.
Meanwhile, ROM should be ok for decrypted devices that flash no_verity zip just after flashing ROM (see my OP on xda)

**Comment by gwolf2u** [comment]
I am aware of no_verity and already added to my op
Setting this from fileencryption to encryptable only makes you not flash no_verity, that's why I asked what should we do
I would wait a few more days for TWRP but if no update comes, will go by changing this in my builds
