### ISSUE TITLE
new Vulkan Drivers

### ISSUE THREAD

**Issue by umerov1999** [crdroidandroid/android_device_oneplus_msm8998-common#10]
I tested new drivers version 1.1.128 from android 11 branch to android 10. They work successfully

**Comment by umerov1999** [comment]
![Screenshot_20201203-142825_Vulkan_Caps_Viewer](https://user-images.githubusercontent.com/3888404/101012067-d3736b80-3573-11eb-8d12-b0723e9e97e4.png)
![Screenshot_20201203-142816_Vulkan_Caps_Viewer](https://user-images.githubusercontent.com/3888404/101012117-d5d5c580-3573-11eb-98c8-38baf61a2305.png)

**Comment by neobuddy89** [comment]
There are some issues with OpenGL .. need to check.

**Comment by umerov1999** [comment]
> There are some issues with OpenGL .. need to check.

vulkan games work (UE4), but doesn't work screen recorder

**Comment by umerov1999** [comment]
Doesn't work screen recorder

**Comment by neobuddy89** [comment]
Added newer vulkan and graphics driver from Pixel.
