### ISSUE TITLE
Reboots after turning on mobile data

### ISSUE THREAD

**Issue by Cipheriax** [crdroidandroid/android_device_oneplus_msm8998-common#12]
I get random reboots on my OnePlus 5T (dumpling) when doing things like turning on data for example - every time when turning on data, not just once every x times. After the reboot data is turned on and is working. When switching data off and on again, it reboots again... didn't happen when I was on OxygenOS, the stock rom, or LineageOS years ago. Turning data off doesn't make it reboot, only when turning it on.

I'm using latest crdroid 7.8 (from July 24th 2021) + nova launcher prime. Issue also occurs when selecting crDroid as launcher app.

edit: I added some logs from Matlog since that logging app was preinstalled and I thought it could maybe help solving this. The _2021-09-13-14-00-39.txt_ file was recorded manually before turning on data, and when my device rebooted the recording apparently stopped, so I attached the newer log as well.
[logcat.txt](https://github.com/crdroidandroid/crdroid_features/files/7154085/logcat.txt)
[2021-09-13-14-00-39.txt](https://github.com/crdroidandroid/crdroid_features/files/7154086/2021-09-13-14-00-39.txt)
[device_info.txt](https://github.com/crdroidandroid/crdroid_features/files/7154087/device_info.txt)

**Comment by Cipheriax** [comment]
after continuing with looking for a solution, I randomly found [some post on xda](https://forum.xda-developers.com/t/rom-official-nightlies-lineageos-17-1.4109617/page-25#post-84172101) as well as an [issue opened up on LOS' git](https://gitlab.com/LineageOS/issues/android/-/issues/2385) and I tried out what they suggested, didn't help much. First I thought it fixed it, but disabling data and enabling it again just results in another reboot. I also removed any modifications on allowance of data usage on the apps, but that neither helped.
This issue seems to be not very new (at least on LOS, but crDroid is based on LOS I think...?) and older threads on this topic, like the one linked previously, have been closed with no comment whatsoever so I don't know what that really means for me now... I'd be happy to assist you in any way possible for me to solve this!

**Comment by gwolf2u** [comment]
@neobuddy89 still supported?

**Comment by Cipheriax** [comment]
made another log, this time through adb. I'm not experienced with logcat so I don't know if it makes a difference whether I log it from pc with adb or on the device with an app. I thought maybe through adb it also catches everything while the phone restarts(?)
...anyway: [log.txt](https://github.com/crdroidandroid/android_device_oneplus_msm8998-common/files/7192479/log.txt)
Notice how the first time enabling data was fine, and the second time it caused a reboot like it always does. It's seemlingly random. Maybe you can see what's going on? @neobuddy89

**Comment by gwolf2u** [comment]
closed for inactivity

**Comment by Cipheriax** [comment]
> closed for inactivity

how so? what am I supposed to write, it never got answered. Issue still persists.

I even did another clean install, this time using flame gapps basic instead of opengapps pico. For testing I turned off mobile data usage for play store, and big surprise, the reboot still occurs. Hope this new log helps. I also swapped sim card slots.
As I said, I'm willing to help with anything I can do, but this doesn't seem the correct place as it's apparently not really actively used. I uploaded some other logs at some time in Telegram, the one uploaded on this post here is the most recent I made.
[2_5357170252272636185.txt](https://github.com/crdroidandroid/android_device_oneplus_msm8998-common/files/7231916/2_5357170252272636185.txt)

**Comment by Cipheriax** [comment]
@gwolf2u forgot to mention. see above please ^

**Comment by gwolf2u** [comment]
sorry but not much can do
not the device I own and maintain
your issue might be something else entirely also
your best bet for now is to ask for support in dedicated forum as GitHub is more intended for code issues
