### ISSUE TITLE
not work nfc

### ISSUE THREAD

**Issue by umerov1999** [crdroidandroid/android_device_oneplus_msm8998-common#9]
msm8998-common: Switch to NqNfc commit crashed nfc, and interface not worked. log - can't open /system/lib64/libp61-jcop-kit.so

**Comment by umerov1999** [comment]
i replace patch for libraries
![Screenshot_20201118-131514_Termux](https://user-images.githubusercontent.com/3888404/99517325-4a1f3f00-29a0-11eb-814b-ab5d6ec6b3cf.png)

**Comment by neobuddy89** [comment]
ROM, Android version?

**Comment by umerov1999** [comment]
> ROM, Android version?

Android 10, LineageOS

**Comment by neobuddy89** [comment]
Try remove
/data/nfc
/data/vendor/nfc
Then reboot
